# Generated by Django 4.1.3 on 2022-11-21 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=25)),
                ('employe_name', models.CharField(max_length=30)),
                ('employe_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_starting_date', models.DateTimeField()),
                ('leave_ending_date', models.DateTimeField()),
                ('leave_applying_date', models.DateTimeField(auto_now_add=True)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.employe')),
            ],
        ),
    ]
