# Generated by Django 4.1.3 on 2022-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
