# Generated by Django 4.1.3 on 2022-11-21 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_leaveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='employe_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_applying_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_starting_date',
            field=models.DateField(),
        ),
    ]
