# Generated by Django 4.1.3 on 2022-11-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0004_employe_email_employe_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
