# Generated by Django 4.1.3 on 2022-11-23 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_employe_total_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
